name: deploy-to-static-sites

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - run: npm install
    - run: echo PUBLIC_URL=. > ./.env
    - run: echo IMAGE_INLINE_SIZE_LIMIT=100000 >> ./.env
    - run: npm run build
    - name: GitHub Pages
      uses: crazy-max/ghaction-github-pages@v1.2.5
      with:
        build_dir:  build
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
    - name: Deploy static to Tencent COS
      uses: TencentCloud/cos-action@v1
      with:
        secret_id: ${{ secrets.SECRET_ID }}
        secret_key: ${{ secrets.SECRET_KEY }}
        cos_bucket: ${{ secrets.COS_BUCKET }}
        cos_region: ${{ secrets.COS_REGION }}
        local_path: build
        remote_path: /
        clean: true
    - name: Deploy static to Tencent CloudBase
      id: deployStatic
      uses: TencentCloudBase/cloudbase-action@v1.1.1
      with:
        secretId: ${{ secrets.SECRET_ID }}
        secretKey: ${{ secrets.SECRET_KEY }}
        envId: ${{ secrets.ENV_ID }}
        staticSrcPath: build
